name: Публикация документации

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  deploy-docs:
    uses: autumn-library/workflows/.github/workflows/deploy-docs.yml@main
    with:
      github_repository: nixel2007/extends
    secrets: inherit
